# Generated by Django 6.0.1 on 2026-01-27 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_event_location_event_price_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.PositiveIntegerField(default=0, help_text='Minimum age required (0 = no restriction)'),
        ),
        migrations.CreateModel(
            name='DigitalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', "Driver's License"), ('national_id', 'National ID'), ('student_id', 'Student ID'), ('birth_certificate', 'Birth Certificate')], max_length=20)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('document_image', models.ImageField(upload_to='digital_ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital ID',
                'verbose_name_plural': 'Digital IDs',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_result', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied - Age Restricted'), ('denied_unverified', 'Denied - ID Not Verified'), ('denied_expired', 'Denied - ID Expired')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_age', models.PositiveIntegerField(blank=True, null=True)),
                ('required_age', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='bookings.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('digital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.digitalid')),
            ],
            options={
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
