# Generated by Django 6.0.2 on 2026-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_event_age_restriction_digitalid_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitalid',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='age_restriction',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='DigitalID',
        ),
    ]
